Num: 3
Umax: 8
Vmax: 6
avoid.m: 10
buffer: 0.03
bug.bug_step_size: 0.5
bug.inflated_size: 7.199999999999999
bug.num_tracks: 2
episodes: 330
physical_radius: 0.3
radius: 0.6
zr.lower_limit_Square_side_length: 22.360679774997898
zr.more_inflated_size: 8.999999999999998
zr.ob_num: 1
zr.ob_rate: 0.2
zr.set_xlim: 50
zr.set_ylim: 50
zr.upper_limit_Square_side_length: 22.360679774997898
