agent.Num: 110
agent.Umax: 10.0
agent.Vmax: 4.6000000000000005
agent.physical_radius: 0.25
agent.radius: 1.0
bug.bug_step_size: 20
bug.lower_limit_inflated_size: 9.0
bug.num_tracks: 4
bug.upper_limit_inflated_size: 14.0
map.set_xlim: 40
map.set_ylim: 30
map.set_zlim: 330
model.SpaceEnvironmentModel.dimension: 2
model.SpaceEnvironmentModel.withObstacles: true
model.TypicalScene.id: Random
model.UnmannedSystem.id: unmanned_vehicle
mpc.K: -1
mpc.epsilon: -1
mpc.max_episode: 50
ob.apart_num: 2
ob.lower_limit_Square_side_length: 45.405712670140126
ob.num: 9
ob.rate: 0.22
ob.upper_limit_Square_side_length: 45.405712670140126
round.current: 1
round.only_one: true
round.total: 1
