# 障碍物路径规划参数
# 从UAV分析结果生成的场景

# ==================== 智能体参数 ====================
agent.Num: 10
agent.Umax: 10.0
agent.Vmax: 3.0
agent.physical_radius: 0.2
agent.radius: 0.8

# 智能体初始位置
ini_x:
    - [30.00, 30.00]
    - [30.00, 30.00]
    - [30.00, 30.00]
    - [30.00, 30.00]
    - [30.00, 30.00]
    - [30.00, 30.00]
    - [30.00, 30.00]
    - [30.00, 30.00]
    - [138.76, 30.00]
    - [138.76, 30.00]

# 智能体目标位置
target:
    - [58.15, 280.65]
    - [58.15, 280.65]
    - [58.15, 280.65]
    - [58.15, 280.65]
    - [58.15, 280.65]
    - [58.92, 254.72]
    - [285.71, 249.12]
    - [285.71, 249.12]
    - [58.15, 280.65]
    - [58.15, 280.65]

# 智能体类型列表
type_list:
    - unicycle

# 智能体控制增益
K: 1.0

# ==================== 地图参数 ====================
map.set_xlim: 330
map.set_ylim: 330
map.set_zlim: 330

# ==================== 障碍物参数 ====================
ob.apart_num: 2
ob.lower_limit_Square_side_length: 20.56194904089777
ob.num: 9
ob.rate: 0.05
ob.upper_limit_Square_side_length: 20.56194904089777

# ==================== BUG算法参数 ====================
bug.bug_step_size: 20
bug.lower_limit_inflated_size: 7.2
bug.num_tracks: 4
bug.upper_limit_inflated_size: 11.2

# ==================== 其他参数 ====================
baseline_bool: false
model.SpaceEnvironmentModel.dimension: 2
model.SpaceEnvironmentModel.withObstacles: true
model.TypicalScene.id: Random
model.UnmannedSystem.id: unmanned_vehicle
mpc.K: -1
mpc.epsilon: -1
mpc.max_episode: 2200
round.current: 1
round.only_one: false
round.total: 1
