# Diverse UAV Scenario - All paths are different
# Agent 0-3: From base [30,30], different targets
# Agent 4-6: From spread base positions, various targets
# Agent 7-9: From different base, scattered targets

# ==================== Agent Parameters ====================
agent.Num: 10
agent.Umax: 10.0
agent.Vmax: 3.0
agent.physical_radius: 0.2
agent.radius: 0.8

# Agent Start Positions (10 different positions)
ini_x:
    - [30, 30]
    - [30, 30]
    - [30, 30]
    - [30, 30]
    - [100, 30]
    - [180, 30]
    - [240, 30]
    - [300, 30]
    - [30, 100]
    - [30, 200]

# Agent Target Positions (10 different targets)
target:
    - [45, 280]
    - [100, 290]
    - [150, 250]
    - [200, 200]
    - [280, 100]
    - [250, 150]
    - [280, 280]
    - [150, 50]
    - [280, 200]
    - [300, 250]

# Agent Types
type_list:
    - unicycle
    - Mecanum
    - Quadcopter
    - patrol_missile
    - fixed_wing
    - unicycle
    - Mecanum
    - Quadcopter
    - patrol_missile
    - fixed_wing

# Control Gain
K: 1.0

# ==================== Map Parameters ====================
map.set_xlim: 330
map.set_ylim: 330
map.set_zlim: 330

# ==================== Obstacle Parameters ====================
ob.apart_num: 2
ob.lower_limit_Square_side_length: 20.56194904089777
ob.num: 9
ob.rate: 0.05
ob.upper_limit_Square_side_length: 20.56194904089777

# ==================== BUG Algorithm Parameters ====================
bug.bug_step_size: 20
bug.lower_limit_inflated_size: 7.2
bug.num_tracks: 4
bug.upper_limit_inflated_size: 11.2

# ==================== Other Parameters ====================
baseline_bool: false
model.SpaceEnvironmentModel.dimension: 2
model.SpaceEnvironmentModel.withObstacles: true
model.TypicalScene.id: Random
model.UnmannedSystem.id: unmanned_vehicle
mpc.K: -1
mpc.epsilon: -1
mpc.max_episode: 2200
round.current: 1
round.only_one: false
round.total: 1
