agent.Num: 5
agent.Umax: 10.0
agent.Vmax: 3.0
agent.physical_radius: 0.2
agent.radius: 0.8

ini_x:
    - [30, 30]
    - [150, 30]
    - [280, 30]
    - [100, 150]
    - [30, 250]

target:
    - [300, 30]
    - [30, 280]
    - [30, 30]
    - [300, 300]
    - [280, 30]

type_list:
    - unicycle
    - Mecanum
    - Quadcopter
    - patrol_missile
    - fixed_wing

K: 1.0

map.set_xlim: 330
map.set_ylim: 330
map.set_zlim: 330

ob.apart_num: 2
ob.lower_limit_Square_side_length: 20.56194904089777
ob.num: 2
ob.rate: 0.05
ob.upper_limit_Square_side_length: 20.56194904089777

obstacle_list:
    - [150, 150, 50]
    - [220, 80, 40]

bug.bug_step_size: 20
bug.lower_limit_inflated_size: 7.2
bug.num_tracks: 4
bug.upper_limit_inflated_size: 11.2

baseline_bool: false
model.SpaceEnvironmentModel.dimension: 2
model.SpaceEnvironmentModel.withObstacles: true
model.TypicalScene.id: Random
model.UnmannedSystem.id: unmanned_vehicle
mpc.K: -1
mpc.epsilon: -1
mpc.max_episode: 2200
round.current: 1
round.only_one: false
round.total: 1
