agent.Num: 10
agent.Umax: 10.0
agent.Vmax: 3.0
agent.physical_radius: 0.2
agent.radius: 0.8

ini_x:
    - [30.0, 30.0]
    - [30.0, 30.0]
    - [30.0, 30.0]
    - [30.0, 30.0]
    - [30.0, 30.0]
    - [30.0, 30.0]
    - [30.0, 30.0]
    - [30.0, 30.0]
    - [30.0, 30.0]
    - [30.0, 30.0]

target:
    - [58.15, 280.65]
    - [58.15, 280.65]
    - [58.15, 280.65]
    - [58.15, 280.65]
    - [58.15, 280.65]
    - [58.92, 254.72]
    - [58.92, 254.72]
    - [58.92, 254.72]
    - [58.92, 254.72]
    - [58.92, 254.72]

type_list:
    - unicycle
    - Mecanum
    - Quadcopter
    - patrol_missile
    - fixed_wing
    - unicycle
    - Mecanum
    - Quadcopter
    - patrol_missile
    - fixed_wing
    - unicycle
    - Mecanum

K: 1.0

map.set_xlim: 330
map.set_ylim: 330
map.set_zlim: 330

ob.apart_num: 2
ob.lower_limit_Square_side_length: 20.56194904089777
ob.num: 9
ob.rate: 0.05
ob.upper_limit_Square_side_length: 20.56194904089777

obstacle_list:
    - [50, 100, 30]
    - [200, 50, 30]
    - [100, 200, 30]
    - [150, 150, 30]
    - [250, 200, 30]
    - [80, 250, 30]
    - [280, 100, 30]
    - [180, 80, 30]
    - [250, 280, 30]

bug.bug_step_size: 20
bug.lower_limit_inflated_size: 7.2
bug.num_tracks: 4
bug.upper_limit_inflated_size: 11.2

baseline_bool: false
model.SpaceEnvironmentModel.dimension: 2
model.SpaceEnvironmentModel.withObstacles: true
model.TypicalScene.id: Random
model.UnmannedSystem.id: unmanned_vehicle
mpc.K: -1
mpc.epsilon: -1
mpc.max_episode: 2200
round.current: 1
round.only_one: false
round.total: 1
